In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('07-06-2021-TO-07-06-2026-ADANIENT-ALL-N.csv')
data.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,ADANIENT,BL,05-Jun-2026,"2,435.60","2,913.40","2,913.40","2,913.40","2,913.40","2,913.40","2,913.40","1,64,39,984","47,89,62,49,385.60",1,-,-
1,ADANIENT,EQ,05-Jun-2026,"2,972.80","2,992.00","3,059.80","2,921.80","3,043.00","3,048.20","3,015.26","56,17,327","16,93,77,06,264.00","1,60,264","15,61,092",27.79
2,ADANIENT,EQ,04-Jun-2026,"2,925.60","2,920.00","2,983.00","2,918.10","2,977.90","2,972.80","2,962.79","17,22,991","5,10,48,60,412.80","81,942","5,50,824",31.97
3,ADANIENT,EQ,03-Jun-2026,"2,968.10","2,960.00","2,965.00","2,888.10","2,929.00","2,925.60","2,922.19","13,46,112","3,93,35,97,043.10","61,748","2,73,771",20.34
4,ADANIENT,EQ,02-Jun-2026,"2,909.40","2,885.00","2,975.00","2,865.20","2,972.00","2,968.10","2,918.50","20,66,890","6,03,22,20,472.10","94,022","5,63,670",27.27

In [3]:
data.columns

Index(['Symbol  ', 'Series  ', 'Date  ', 'Prev Close  ', 'Open Price  ',
       'High Price  ', 'Low Price  ', 'Last Price  ', 'Close Price  ',
       'Average Price ', 'Total Traded Quantity  ', 'Turnover ₹  ',
       'No. of Trades  ', 'Deliverable Qty  ', '% Dly Qt to Traded Qty  '],
      dtype='object')

In [4]:
data.columns = data.columns.str.strip()

In [5]:
data = data.reset_index(drop=True)

In [6]:
data.dtypes

Symbol                    object
Series                    object
Date                      object
Prev Close                object
Open Price                object
High Price                object
Low Price                 object
Last Price                object
Close Price               object
Average Price             object
Total Traded Quantity     object
Turnover ₹                object
No. of Trades             object
Deliverable Qty           object
% Dly Qt to Traded Qty    object
dtype: object

In [7]:
data.tail(10)

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
1242,ADANIENT,EQ,18-Jun-2021,"1,367.70","1,350.00","1,504.00","1,332.55","1,495.00","1,487.50","1,422.42","3,05,26,777","43,42,18,45,928.35","7,75,906","23,79,125",7.79
1243,ADANIENT,EQ,17-Jun-2021,"1,448.30","1,380.00","1,436.00","1,303.50","1,356.00","1,367.70","1,374.54","2,79,26,070","38,38,54,36,658.55","6,21,898","16,70,288",5.98
1244,ADANIENT,EQ,16-Jun-2021,"1,538.85","1,510.00","1,538.20","1,409.30","1,427.00","1,448.30","1,494.23","1,26,26,149","18,86,63,31,555.40","2,90,100","13,31,114",10.54
1245,ADANIENT,EQ,15-Jun-2021,"1,501.45","1,550.95","1,572.60","1,477.20","1,525.80","1,538.85","1,525.74","2,23,20,542","34,05,52,51,940.05","5,79,380","12,41,986",5.56
1246,ADANIENT,EQ,14-Jun-2021,"1,601.60","1,441.45","1,529.95","1,201.20","1,510.35","1,501.45","1,372.66","4,35,30,006","59,75,16,84,972.35","11,25,572","31,93,722",7.34
1247,ADANIENT,EQ,11-Jun-2021,"1,612.00","1,615.10","1,620.10","1,575.25","1,601.00","1,601.60","1,599.37","53,55,387","8,56,52,56,925.95","1,13,482","11,78,956",22.01
1248,ADANIENT,EQ,10-Jun-2021,"1,594.65","1,612.00","1,630.00","1,591.00","1,609.80","1,612.00","1,609.08","53,62,307","8,62,83,79,885.05","1,14,278","10,47,267",19.53
1249,ADANIENT,EQ,09-Jun-2021,"1,636.45","1,640.00","1,649.45","1,571.85","1,590.45","1,594.65","1,610.46","1,16,14,666","18,70,49,33,129.65","2,49,405","21,70,768",18.69
1250,ADANIENT,EQ,08-Jun-2021,"1,624.30","1,633.00","1,668.00","1,602.45","1,633.00","1,636.45","1,633.09","1,24,10,257","20,26,70,43,634.75","2,69,336","12,32,732",9.93
1251,ADANIENT,EQ,07-Jun-2021,"1,700.95","1,715.00","1,717.20","1,613.00","1,625.00","1,624.30","1,654.64","1,53,50,263","25,39,91,88,226.90","3,52,456","21,75,944",14.18

In [8]:
data.head(10)

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,ADANIENT,BL,05-Jun-2026,"2,435.60","2,913.40","2,913.40","2,913.40","2,913.40","2,913.40","2,913.40","1,64,39,984","47,89,62,49,385.60",1,-,-
1,ADANIENT,EQ,05-Jun-2026,"2,972.80","2,992.00","3,059.80","2,921.80","3,043.00","3,048.20","3,015.26","56,17,327","16,93,77,06,264.00","1,60,264","15,61,092",27.79
2,ADANIENT,EQ,04-Jun-2026,"2,925.60","2,920.00","2,983.00","2,918.10","2,977.90","2,972.80","2,962.79","17,22,991","5,10,48,60,412.80","81,942","5,50,824",31.97
3,ADANIENT,EQ,03-Jun-2026,"2,968.10","2,960.00","2,965.00","2,888.10","2,929.00","2,925.60","2,922.19","13,46,112","3,93,35,97,043.10","61,748","2,73,771",20.34
4,ADANIENT,EQ,02-Jun-2026,"2,909.40","2,885.00","2,975.00","2,865.20","2,972.00","2,968.10","2,918.50","20,66,890","6,03,22,20,472.10","94,022","5,63,670",27.27
5,ADANIENT,EQ,01-Jun-2026,"2,937.40","2,949.90","2,955.70","2,891.10","2,908.00","2,909.40","2,916.39","16,29,342","4,75,18,00,466.00","63,188","6,04,568",37.11
6,ADANIENT,EQ,29-May-2026,"2,973.10","2,987.80","2,995.00","2,926.80","2,940.00","2,937.40","2,946.03","40,40,865","11,90,45,18,687.50","1,02,996","21,46,865",53.13
7,ADANIENT,EQ,27-May-2026,"2,969.30","2,982.00","3,027.50","2,944.00","2,972.80","2,973.10","2,978.58","38,26,916","11,39,87,80,340.80","1,09,903","8,79,795",22.99
8,ADANIENT,EQ,26-May-2026,"2,849.70","2,846.00","2,979.40","2,825.00","2,973.00","2,969.30","2,920.76","48,99,494","14,31,02,55,450.50","1,47,603","12,71,864",25.96
9,ADANIENT,EQ,25-May-2026,"2,717.30","2,739.80","2,858.80","2,739.30","2,847.00","2,849.70","2,816.47","32,77,924","9,23,21,60,983.80","1,23,831","10,11,681",30.86

In [9]:
equity = data[data['Series']=='EQ']

In [10]:
equity[equity['Date']>'18-Jun-2021']

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
6,ADANIENT,EQ,29-May-2026,"2,973.10","2,987.80","2,995.00","2,926.80","2,940.00","2,937.40","2,946.03","40,40,865","11,90,45,18,687.50","1,02,996","21,46,865",53.13
7,ADANIENT,EQ,27-May-2026,"2,969.30","2,982.00","3,027.50","2,944.00","2,972.80","2,973.10","2,978.58","38,26,916","11,39,87,80,340.80","1,09,903","8,79,795",22.99
8,ADANIENT,EQ,26-May-2026,"2,849.70","2,846.00","2,979.40","2,825.00","2,973.00","2,969.30","2,920.76","48,99,494","14,31,02,55,450.50","1,47,603","12,71,864",25.96
9,ADANIENT,EQ,25-May-2026,"2,717.30","2,739.80","2,858.80","2,739.30","2,847.00","2,849.70","2,816.47","32,77,924","9,23,21,60,983.80","1,23,831","10,11,681",30.86
10,ADANIENT,EQ,22-May-2026,"2,697.60","2,710.20","2,745.00","2,706.10","2,719.10","2,717.30","2,724.58","10,94,843","2,98,29,87,107.30","45,849","2,69,273",24.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1237,ADANIENT,EQ,25-Jun-2021,"1,508.50","1,525.00","1,534.00","1,501.00","1,516.00","1,519.45","1,518.09","49,62,963","7,53,42,02,901.05","94,791","6,12,539",12.34
1238,ADANIENT,EQ,24-Jun-2021,"1,504.75","1,509.95","1,519.00","1,488.05","1,515.35","1,508.50","1,503.94","72,61,764","10,92,12,78,765.30","1,60,280","8,94,034",12.31
1239,ADANIENT,EQ,23-Jun-2021,"1,541.60","1,560.10","1,569.95","1,481.30","1,499.70","1,504.75","1,513.21","1,26,79,703","19,18,70,59,087.85","2,65,370","20,28,193",16.00
1240,ADANIENT,EQ,22-Jun-2021,"1,540.00","1,554.05","1,582.00","1,531.80","1,542.10","1,541.60","1,563.12","1,20,69,983","18,86,68,44,732.70","2,69,773","12,23,905",10.14
1241,ADANIENT,EQ,21-Jun-2021,"1,487.50","1,490.00","1,582.00","1,444.85","1,531.00","1,540.00","1,533.82","2,11,01,083","32,36,52,48,197.10","5,43,336","10,03,919",4.76

In [11]:
data['Series'].value_counts()

Series
EQ    1240
BL      12
Name: count, dtype: int64

In [12]:
cols = [
    'Open Price',
    'High Price',
    'Low Price',
    'Close Price',
    'Last Price',
    'Average Price',
    'Prev Close',
    'Total Traded Quantity',
    'No. of Trades',
    'Deliverable Qty',

    
]

for col in cols:
    data[col] = (
        data[col]
        .astype(str)
        .str.replace(',', '',regex=False)
        .str.replace('_','',regex=False)
    )
    data[col] = pd.to_numeric(data[col], errors='coerce')

In [13]:
data.isnull().sum()

Symbol                     0
Series                     0
Date                       0
Prev Close                 0
Open Price                 0
High Price                 0
Low Price                  0
Last Price                 0
Close Price                0
Average Price              0
Total Traded Quantity      0
Turnover ₹                 0
No. of Trades              0
Deliverable Qty           12
% Dly Qt to Traded Qty     0
dtype: int64

In [14]:
data.dtypes

Symbol                     object
Series                     object
Date                       object
Prev Close                float64
Open Price                float64
High Price                float64
Low Price                 float64
Last Price                float64
Close Price               float64
Average Price             float64
Total Traded Quantity       int64
Turnover ₹                 object
No. of Trades               int64
Deliverable Qty           float64
% Dly Qt to Traded Qty     object
dtype: object

In [15]:
print(data['Last Price'].dtype)

float64

In [16]:
data['Last Price'].astype(str).unique()

array(['2913.4', '3043.0', '2977.9', ..., '1609.8', '1590.45', '1625.0'],
      dtype=object)

In [17]:
data.head()

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,ADANIENT,BL,05-Jun-2026,2435.6,2913.4,2913.4,2913.4,2913.4,2913.4,2913.40,16439984,"47,89,62,49,385.60",1,NaN,-
1,ADANIENT,EQ,05-Jun-2026,2972.8,2992.0,3059.8,2921.8,3043.0,3048.2,3015.26,5617327,"16,93,77,06,264.00",160264,1561092.0,27.79
2,ADANIENT,EQ,04-Jun-2026,2925.6,2920.0,2983.0,2918.1,2977.9,2972.8,2962.79,1722991,"5,10,48,60,412.80",81942,550824.0,31.97
3,ADANIENT,EQ,03-Jun-2026,2968.1,2960.0,2965.0,2888.1,2929.0,2925.6,2922.19,1346112,"3,93,35,97,043.10",61748,273771.0,20.34
4,ADANIENT,EQ,02-Jun-2026,2909.4,2885.0,2975.0,2865.2,2972.0,2968.1,2918.50,2066890,"6,03,22,20,472.10",94022,563670.0,27.27

In [18]:
data.isnull().sum()

Symbol                     0
Series                     0
Date                       0
Prev Close                 0
Open Price                 0
High Price                 0
Low Price                  0
Last Price                 0
Close Price                0
Average Price              0
Total Traded Quantity      0
Turnover ₹                 0
No. of Trades              0
Deliverable Qty           12
% Dly Qt to Traded Qty     0
dtype: int64

In [19]:
data[data['No. of Trades']==1]

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover ₹,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,ADANIENT,BL,05-Jun-2026,2435.60,2913.40,2913.40,2913.40,2913.40,2913.40,2913.40,16439984,"47,89,62,49,385.60",1,NaN,-
17,ADANIENT,BL,14-May-2026,2462.00,2435.60,2435.60,2435.60,2435.60,2435.60,2435.60,5892423,"14,35,15,85,458.80",1,NaN,-
137,ADANIENT,BL,18-Nov-2025,2558.70,2462.00,2462.00,2462.00,2462.00,2462.00,2462.00,5342008,"13,15,20,23,696.00",1,NaN,-
224,ADANIENT,BL,14-Jul-2025,4008.85,2558.70,2558.70,2558.70,2558.70,2558.70,2558.70,60335,"15,43,79,164.50",1,NaN,-
886,ADANIENT,BL,14-Nov-2022,3580.70,4008.85,4008.85,4008.85,4008.85,4008.85,4008.85,434843,"1,74,32,20,360.55",1,NaN,-
893,ADANIENT,BL,03-Nov-2022,3309.80,3580.70,3580.70,3580.70,3580.70,3580.70,3580.70,434844,"1,55,70,45,910.80",1,NaN,-
901,ADANIENT,BL,25-Oct-2022,3246.25,3309.80,3309.80,3309.80,3309.80,3309.80,3309.80,233946,"77,43,14,470.80",1,NaN,-
912,ADANIENT,BL,11-Oct-2022,3455.75,3246.25,3246.25,3246.25,3246.25,3246.25,3246.25,359499,"1,16,70,23,628.75",1,NaN,-
917,ADANIENT,BL,03-Oct-2022,2698.40,3455.75,3455.75,3455.75,3455.75,3455.75,3455.75,359712,"1,24,30,74,744.00",1,NaN,-
956,ADANIENT,BL,08-Aug-2022,2499.40,2698.40,2698.40,2698.40,2698.40,2698.40,2698.40,324759,"87,63,29,685.60",1,NaN,-
967,ADANIENT,BL,25-Jul-2022,1458.70,2499.40,2499.40,2499.40,2499.40,2499.40,2499.40,324759,"81,17,02,644.60",1,NaN,-
1168,ADANIENT,BL,04-Oct-2021,505.00,1458.70,1458.70,1458.70,1458.70,1458.70,1458.70,264774,"38,62,25,833.80",1,NaN,-

In [20]:
equity.isnull().sum()

Symbol                    0
Series                    0
Date                      0
Prev Close                0
Open Price                0
High Price                0
Low Price                 0
Last Price                0
Close Price               0
Average Price             0
Total Traded Quantity     0
Turnover ₹                0
No. of Trades             0
Deliverable Qty           0
% Dly Qt to Traded Qty    0
dtype: int64

In [21]:
equity.dtypes

Symbol                    object
Series                    object
Date                      object
Prev Close                object
Open Price                object
High Price                object
Low Price                 object
Last Price                object
Close Price               object
Average Price             object
Total Traded Quantity     object
Turnover ₹                object
No. of Trades             object
Deliverable Qty           object
% Dly Qt to Traded Qty    object
dtype: object

In [22]:
cols = [
    'Open Price',
    'High Price',
    'Low Price',
    'Close Price',
    'Last Price',
    'Average Price',
    'Prev Close',
    'Total Traded Quantity',
    'No. of Trades',
    'Deliverable Qty',

    
]

for col in cols:
    equity[col] = (
        equity[col]
        .astype(str)
        .str.replace(',', '',regex=False)
        .str.replace('_','',regex=False)
    )
    equity[col] = pd.to_numeric(equity[col], errors='coerce')

/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = (
/var/folders/lm/hds0rx213vscl9tcfy526l200000gn/T/ipykernel_2729/383860429.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  equity[col] = pd.to_numeric(equity[col], errors='coerce')

In [23]:
data['Turnover ₹'] = pd.to_numeric(data['Turnover ₹'],errors = 'coerce')

In [24]:
equity = equity.rename(columns={'Turnover ₹':'Turnover'})

In [25]:
equity['Turnover'] = (
    equity['Turnover']
    .astype(str)
    .str.replace(',', '', regex=False)
)

equity['Turnover'] = pd.to_numeric(
    equity['Turnover'],
    errors='coerce'
)

In [30]:
equity

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
1,ADANIENT,EQ,2026-06-05,2972.80,2992.0,3059.80,2921.80,3043.00,3048.20,3015.26,5617327,1.693771e+10,160264,1561092,27.79
2,ADANIENT,EQ,2026-06-04,2925.60,2920.0,2983.00,2918.10,2977.90,2972.80,2962.79,1722991,5.104860e+09,81942,550824,31.97
3,ADANIENT,EQ,2026-06-03,2968.10,2960.0,2965.00,2888.10,2929.00,2925.60,2922.19,1346112,3.933597e+09,61748,273771,20.34
4,ADANIENT,EQ,2026-06-02,2909.40,2885.0,2975.00,2865.20,2972.00,2968.10,2918.50,2066890,6.032220e+09,94022,563670,27.27
5,ADANIENT,EQ,2026-06-01,2937.40,2949.9,2955.70,2891.10,2908.00,2909.40,2916.39,1629342,4.751800e+09,63188,604568,37.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247,ADANIENT,EQ,2021-06-11,1612.00,1615.1,1620.10,1575.25,1601.00,1601.60,1599.37,5355387,8.565257e+09,113482,1178956,22.01
1248,ADANIENT,EQ,2021-06-10,1594.65,1612.0,1630.00,1591.00,1609.80,1612.00,1609.08,5362307,8.628380e+09,114278,1047267,19.53
1249,ADANIENT,EQ,2021-06-09,1636.45,1640.0,1649.45,1571.85,1590.45,1594.65,1610.46,11614666,1.870493e+10,249405,2170768,18.69
1250,ADANIENT,EQ,2021-06-08,1624.30,1633.0,1668.00,1602.45,1633.00,1636.45,1633.09,12410257,2.026704e+10,269336,1232732,9.93
1251,ADANIENT,EQ,2021-06-07,1700.95,1715.0,1717.20,1613.00,1625.00,1624.30,1654.64,15350263,2.539919e+10,352456,2175944,14.18

In [29]:
equity.dtypes

Symbol                            object
Series                            object
Date                      datetime64[ns]
Prev Close                       float64
Open Price                       float64
High Price                       float64
Low Price                        float64
Last Price                       float64
Close Price                      float64
Average Price                    float64
Total Traded Quantity              int64
Turnover                         float64
No. of Trades                      int64
Deliverable Qty                    int64
% Dly Qt to Traded Qty            object
dtype: object

In [28]:
equity['Date'] = pd.to_datetime(equity['Date'],errors = 'coerce')